apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    tier: database
    component: mysql  
spec:
    replicas: 1
    selector:
    # using these labels replica set selects the pod
      matchLabels:  
        project: roboshop
        tier: database
        component: mysql
        # This is pod definition, pod is subset of replicaset
    template:
      metadata:
       namespace: roboshop
       labels:
        project: roboshop
        tier: database
        component: mysql
      spec:
        containers:
        - name: mysql
          image: gaddamakhil/mysql:1.4.0
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
        project: roboshop
        tier: database
        component: mysql
spec:
  selector:
    # labels are used as delectors
        project: roboshop
        tier: database
        component: mysql
  ports:
  - protocol: TCP
    port: 3306 #sevice port (internal cluster IP)
    targetPort: 3306   # container port (must match your Pod's containerPort)          